name: music_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:

  flutter:
    sdk: flutter
  path: any
  transparent_image:
  dio:
  hive:
  hive_flutter:
  flutter_bloc:
  cached_network_image: ^3.3.0
  just_audio:
  audio_video_progress_bar: ^2.0.1
  email_validator: ^2.1.16
  firebase_auth:   
  cloud_firestore: 
  google_sign_in: ^6.1.6



  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  
  
  flutter_lints: ^2.0.0



flutter:

 
  uses-material-design: true
  assets:
      - assets/images/artist_image.png
      - assets/images/logo.png
      - assets/images/onboarding.png

      - assets/songs/song.mp3

 